title: MoneroKon 2024
description: A conference in privacy-enhancing technologies and distributed systems
logo: /assets/img/monerokon-logo.png
show_downloads: false
google_analytics: 
theme: jekyll-theme-minimal
