title: MoneroKon 2024
description: A technical conference in privacy and financial technology
logo: /assets/img/monerokon-logo.png
show_downloads: false
google_analytics: 
theme: jekyll-theme-minimal
