title: MoneroKon
description: A conference & hackathon in privacy-enhancing technologies and distributed systems
logo: /assets/img/monerokon-logo.png
show_downloads: false
google_analytics: 
theme: jekyll-theme-minimal
