title: Monero Konferenco 2023
logo: /assets/img/logo.jpg
description: TBD - 
    * La Fabrika, Prague, Czechia (23rd-26th June 2023) or
    * Neuchâtel University, Switzerland (30th June - 3rd July 2023)
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
